// <auto-generated />
using System;
using EFCoreMvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreMvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreMvc.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Departmen")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Office Email")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnName("Sex")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("FullName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Salary")
                        .IsRequired()
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SomeTestProperty")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Departmen = 3,
                            Email = "wonkulahp@yahoo.com",
                            Gender = "Female",
                            Name = "Precious K Wonkulah",
                            Salary = 30000m,
                            SomeTestProperty = 0
                        },
                        new
                        {
                            EmployeeId = 2,
                            Departmen = 0,
                            Email = "john@gmail.com",
                            Gender = "Male",
                            Name = "John Brown",
                            Salary = 6000m,
                            SomeTestProperty = 0
                        },
                        new
                        {
                            EmployeeId = 3,
                            Departmen = 2,
                            Email = "dacious@hotmail.com",
                            Gender = "Female",
                            Name = "Dacious R Wonkulah",
                            Salary = 250m,
                            SomeTestProperty = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
